import type { ReleaseEntry } from "@/types/site";

const standardStore = {
  en: "Thoughost Bandcamp / Dizzylab",
  zh: "Thoughost Bandcamp / Dizzylab",
  jp: "Thoughost Bandcamp / Dizzylab",
};

function createBandcampLinks(path: string) {
  return [
    {
      platform: "Bandcamp",
      label: "Bandcamp",
      url: `https://thoughost.bandcamp.com${path}`,
    },
  ];
}

function createPurchaseLinks(path: string, dizzylabId?: string) {
  const links: NonNullable<ReleaseEntry["purchaseLinks"]> = [
    {
      label: "Bandcamp",
      url: `https://thoughost.bandcamp.com${path}`,
      kind: "bandcamp" as const,
    },
  ];

  if (dizzylabId) {
    links.push({
      label: "Dizzylab",
      url: `https://www.dizzylab.net/d/${dizzylabId}`,
      kind: "dizzylab" as const,
    });
  }

  return links;
}

function createBandcampPrice(amount: number) {
  const formatted = amount.toLocaleString("en-US");

  return {
    en: `¥${formatted} JPY or more`,
    zh: `¥${formatted} JPY 起`,
    jp: `¥${formatted} JPY〜`,
  };
}

const nameYourPrice = {
  en: "Name your price",
  zh: "自定价格",
  jp: "Name your price",
};

function createTracklist(tracks: string[]) {
  return {
    en: tracks,
    zh: tracks,
    jp: tracks,
  };
}

function createDetailedTracks(tracks: Array<{ number?: string; title: string; artist?: string; disc?: string }>) {
  return {
    en: tracks,
    zh: tracks,
    jp: tracks,
  };
}

function createUniformArtistTracks(tracks: string[], artist: string) {
  return createDetailedTracks(
    tracks.map((title, index) => ({
      number: String(index + 1).padStart(2, "0"),
      title,
      artist,
    })),
  );
}

export const releases: ReleaseEntry[] = [
  {
    slug: "2000-invasion",
    title: {
      en: "2000% INVASION",
      zh: "2000% INVASION",
      jp: "2000% INVASION",
    },
    heroTitle: {
      en: "2000%\nINVASION",
      zh: "2000%\nINVASION",
      jp: "2000%\nINVASION",
    },
    artistName: "Thoughost",
    releaseType: "Compilation",
    releaseDate: "2025.10.26",
    subtitle: {
      en: "5th Anniversary Compilation",
      zh: "五周年纪念合集",
      jp: "5周年記念コンピレーション",
    },
    coverImage: "/images/releases/2000-invasion.jpg",
    heroImage: "/images/releases/2000-invasion.jpg",
    summary: {
      en: "A fifth-anniversary compilation that revives turn-of-the-millennium rave energy with euphoric synths, club-scale hooks, and a bright collective rush.",
      zh: "Thoughost 五周年纪念合集，以千禧年前后的 rave 质感为核心，把高亮合成器、俱乐部推进感与群体热量重新点燃。",
      jp: "Thoughost 5周年を記念するコンピレーション。2000年代レイヴの高揚感を、鮮やかなシンセとクラブサイズの推進力で現代に呼び戻す作品です。",
    },
    modelNumber: "THGO-0010",
    price: createBandcampPrice(2500),
    store: {
      en: "DIVERSE DIRECT / Thoughost Bandcamp / Dizzylab",
      zh: "DIVERSE DIRECT / Thoughost Bandcamp / Dizzylab",
      jp: "DIVERSE DIRECT / Thoughost Bandcamp / Dizzylab",
    },
    credits: {
      illustrator: "TARA#376",
      designer: "Konseki Takane",
      mastering: "Joulez",
      producer: "Thoughost",
    },
    tracklist: createTracklist([
      "HIT THE RAVE ANTHEM",
      "Grooooovy↑",
      "Afterglow",
      "Call Me",
      "Lumière",
      "Ravenaissance",
      "New Player Adventure",
      "CATCH THE FIRE feat. Konseki Takane",
      "Better Walk Away",
      "Soda",
      "Surf the Ravenet",
      "Exhausting Mind",
      "Music Is My Savior",
      "Dream So Real",
    ]),
    tracks: createDetailedTracks([
      { number: "01", title: "HIT THE RAVE ANTHEM", artist: "The Operation" },
      { number: "02", title: "Grooooovy↑", artist: "Silent Xords" },
      { number: "03", title: "Afterglow", artist: "Joulez" },
      { number: "04", title: "Call Me", artist: "Nirotiy" },
      { number: "05", title: "Lumière", artist: "うさぎずきん" },
      { number: "06", title: "Ravenaissance", artist: "hapi⇒" },
      { number: "07", title: "New Player Adventure", artist: "Eszett" },
      { number: "08", title: "CATCH THE FIRE feat. Konseki Takane", artist: "Thoughost" },
      { number: "09", title: "Better Walk Away", artist: "slytheta" },
      { number: "10", title: "Soda", artist: "A4" },
      { number: "11", title: "Surf the Ravenet", artist: "Julian T" },
      { number: "12", title: "Exhausting Mind", artist: "RiraN" },
      { number: "13", title: "Music Is My Savior", artist: "M-Project" },
      { number: "14", title: "Dream So Real", artist: "DJ Noriken" },
    ]),
    links: createBandcampLinks("/album/2000-invasion"),
    purchaseLinks: [
      {
        label: "Bandcamp",
        url: "https://thoughost.bandcamp.com/album/2000-invasion",
        kind: "bandcamp",
      },
      {
        label: "Dizzylab",
        url: "https://www.dizzylab.net/d/THGO-0010",
        kind: "dizzylab",
      },
      {
        label: "DIVERSE DIRECT",
        url: "https://www.diverse.direct/thoughost/thgo-0010/",
        kind: "diverse",
      },
    ],
    circleLink: "https://www.diverse.direct/thoughost/",
    itemListLink: "https://www.diverse.direct/itemlist/?circle_id=Thoughost",
    isHero: true,
    isFeatured: true,
  },
  {
    slug: "moonshine-001",
    title: {
      en: "MOONSHINE #001",
      zh: "MOONSHINE #001",
      jp: "MOONSHINE #001",
    },
    artistName: "Thoughost",
    releaseType: "Compilation",
    releaseDate: "2025.10.26",
    modelNumber: "THGO-009",
    price: createBandcampPrice(1500),
    store: standardStore,
    coverImage: "/images/releases/moonshine-001.jpg",
    heroImage: "/images/releases/moonshine-001.jpg",
    summary: {
      en: "An all-techno compilation that moves from pressure-built hypnosis to sharper machine funk, holding eleven different angles of the same nocturnal pulse.",
      zh: "一张以 techno 为主轴的合集，在低频压迫、机械律动与夜色张力之间展开，收录十一种风格各异却互相呼应的切面。",
      jp: "テクノに焦点を当てたコンピレーション。催眠的な反復から硬質なマシン・ファンクまで、夜の鼓動を11通りの視点で束ねています。",
    },
    credits: {
      mastering: "火烧",
      illustrator: "豆腐",
      designer: "豆腐",
    },
    tracklist: createTracklist([
      "long out of nacht",
      "a4",
      "Ground State",
      "BIAS",
      "Disoriented Field",
      "Proc",
      "Acid Cagger",
      "DUNGEON TECH",
      "STAGE 5 GAS",
      "MIRAI",
      "Something out of Your TECHNO",
    ]),
    tracks: createDetailedTracks([
      { number: "01", title: "long out of nacht", artist: "Nirotiy" },
      { number: "02", title: "a4", artist: "A.I." },
      { number: "03", title: "Ground State", artist: "Project-G" },
      { number: "04", title: "BIAS", artist: "潮音きつね" },
      { number: "05", title: "Disoriented Field", artist: "Irish Kappa" },
      { number: "06", title: "Proc", artist: "Yazavva" },
      { number: "07", title: "Acid Cagger", artist: "NANO_TAN" },
      { number: "08", title: "DUNGEON TECH", artist: "FISHY" },
      { number: "09", title: "STAGE 5 GAS", artist: "Y." },
      { number: "10", title: "MIRAI", artist: "KeiuO" },
      { number: "11", title: "Something out of Your TECHNO", artist: "Darkness Peach" },
    ]),
    links: createBandcampLinks("/album/moonshine-001"),
    purchaseLinks: createPurchaseLinks("/album/moonshine-001", "THGO-009"),
    isFeatured: true,
  },
  {
    slug: "haru-no-shuen",
    title: {
      en: "春ノ終焉",
      zh: "春ノ終焉",
      jp: "春ノ終焉",
    },
    artistName: "Joulez, 月見静華",
    releaseType: "Single",
    releaseDate: "2025.07.25",
    modelNumber: "TGSG-002",
    price: nameYourPrice,
    store: standardStore,
    coverImage: "/images/releases/haru-no-shuen.jpg",
    heroImage: "/images/releases/haru-no-shuen.jpg",
    summary: {
      en: "A concise single built around the fading edge of spring, pairing melancholy melody with a clean, focused emotional descent.",
      zh: "一首围绕春日终章展开的单曲，以克制的旋律与下坠式情绪勾出季节结束时的余温。",
      jp: "春の終わり際を切り取ったシングル。抑えた旋律とまっすぐな感情の沈み込みで、季節の余韻を静かに残します。",
    },
    tracklist: createTracklist(["春ノ終焉"]),
    tracks: createUniformArtistTracks(["春ノ終焉"], "Joulez, 月見静華"),
    links: createBandcampLinks("/track/--17"),
    purchaseLinks: createPurchaseLinks("/track/--17", "TGSG-002"),
    isFeatured: true,
  },
  {
    slug: "thoughts",
    title: {
      en: "thoughts",
      zh: "thoughts",
      jp: "thoughts",
    },
    heroTitle: {
      en: "thoughts",
      zh: "thoughts",
      jp: "thoughts",
    },
    artistName: "Thoughost",
    releaseType: "Compilation",
    releaseDate: "2025.04.27",
    modelNumber: "THGO-008",
    price: createBandcampPrice(1500),
    store: standardStore,
    coverImage: "/images/releases/thoughts.jpg",
    heroImage: "/images/releases/thoughts.jpg",
    summary: {
      en: "The opening chapter of a new series that threads one theme through many voices, here centered on rebirth, afterglow, and emotional reset.",
      zh: "新系列的起点，以“rebirth”为统一主题，让多位作者在同一概念下展开各自的再生感、余辉感与情绪复位。",
      jp: "新シリーズの幕開けとなる一作。今回は「rebirth」を軸に、複数のアーティストが再生と余韻をそれぞれの方法で描いています。",
    },
    credits: {
      mastering: "Valtrax",
      illustrator: "TARA#376",
      designer: "Konseki Takane",
    },
    tracklist: createTracklist([
      "palette ii",
      "Awake",
      "幽けきルミノールライト",
      "Lucidandelion",
      "Titania",
      "December",
      "6 p.m.",
      "Voix sacrée",
      "曇天",
      "Epilogue",
    ]),
    tracks: createDetailedTracks([
      { number: "01", title: "palette ii", artist: "VeetaCrush" },
      { number: "02", title: "Awake", artist: "Joulez" },
      { number: "03", title: "幽けきルミノールライト", artist: "潮音きつね" },
      { number: "04", title: "Lucidandelion", artist: "望月真白" },
      { number: "05", title: "Titania", artist: "Aki Sz" },
      { number: "06", title: "December", artist: "かたぎり" },
      { number: "07", title: "6 p.m.", artist: "wheatfox" },
      { number: "08", title: "Voix sacrée", artist: "Nirotiy" },
      { number: "09", title: "曇天", artist: "桃罐" },
      { number: "10", title: "Epilogue", artist: "Rayven" },
    ]),
    links: createBandcampLinks("/album/thoughts"),
    purchaseLinks: createPurchaseLinks("/album/thoughts", "THGO-008"),
    specialLink: "https://thoughost.com/special/thoughts",
    isHero: true,
    isFeatured: true,
  },
  {
    slug: "asteria",
    title: {
      en: "Asteria",
      zh: "Asteria",
      jp: "Asteria",
    },
    artistName: "Joulez",
    releaseType: "Album",
    releaseDate: "2025.04.27",
    modelNumber: "TGEP-003",
    price: createBandcampPrice(1500),
    store: standardStore,
    coverImage: "/images/releases/asteria.jpg",
    heroImage: "/images/releases/asteria.jpg",
    summary: {
      en: "Joulez returns with a solo record shaped by starlight imagery, reflective songwriting, and a second half that refracts the core theme through four remixes.",
      zh: "Joulez 回归后的首张个人作品，以星光意象、抒情结构与四首不同方向的 remix，完整展开同一主题的多重折射。",
      jp: "Joulez が活動再開後に届けたソロ作品。星光のイメージ、内省的な書法、そして4つのリミックスで主題を多面的に広げています。",
    },
    credits: {
      producer: "Joulez",
      mastering: "Joulez",
      designer: "Konseki Takane",
    },
    tracklist: createTracklist([
      "Tessarect of light and stars",
      "Asteria",
      "宙知らぬ星",
      "欠片都市 -the shattered past-",
      "Asteria (AiSS Piano Quartet Arr.)",
      "Asteria (wheatfox's Neural Botany Mix)",
      "Asteria (望月真白's Jungle Mixed Up)",
      "Asteria (Nirotiy's 'Call of Hecate' ver.)",
    ]),
    tracks: createDetailedTracks([
      { number: "01", title: "Tessarect of light and stars", artist: "Joulez" },
      { number: "02", title: "Asteria", artist: "Joulez; Himawari" },
      { number: "03", title: "宙知らぬ星", artist: "Joulez; Himawari" },
      { number: "04", title: "欠片都市 -the shattered past-", artist: "Joulez" },
      { number: "05", title: "Asteria (AiSS Piano Quartet Arr.)", artist: "Joulez / AiSS" },
      { number: "06", title: "Asteria (wheatfox's Neural Botany Mix)", artist: "Joulez / wheatfox" },
      { number: "07", title: "Asteria (望月真白's Jungle Mixed Up)", artist: "Joulez / 望月真白" },
      { number: "08", title: "Asteria (Nirotiy's 'Call of Hecate' ver.)", artist: "Joulez / Nirotiy" },
    ]),
    links: createBandcampLinks("/album/asteria"),
    purchaseLinks: createPurchaseLinks("/album/asteria", "TGEP-003"),
    isFeatured: true,
  },
  {
    slug: "palette-of-clouds",
    title: {
      en: "palette of clouds",
      zh: "palette of clouds",
      jp: "palette of clouds",
    },
    artistName: "Nirotiy",
    releaseType: "EP",
    releaseDate: "2024.10.27",
    modelNumber: "TGEP-002",
    price: createBandcampPrice(500),
    store: standardStore,
    coverImage: "/images/releases/palette-of-clouds.jpg",
    heroImage: "/images/releases/palette-of-clouds.jpg",
    summary: {
      en: "Nirotiy’s first EP turns cloud forms into emotional weather, painting quiet scenes with airy atmosphere, freeform motion, and soft scientific wonder.",
      zh: "Nirotiy 的首张 EP 把云层形态转化为情绪天气，用轻盈空间、自由流动与一点天文式观察去描绘不同场景。",
      jp: "Nirotiy の1st EP。雲の形を感情の天候へと置き換え、軽やかな空気感と自由な流れで静かな風景を描いています。",
    },
    tracklist: createTracklist([
      "cirrostratus fibratus",
      "stratocumulus undulatus",
      "cumulonimbus",
      "noctilucent clouds",
      "nimbostratus (2024)",
    ]),
    tracks: createUniformArtistTracks(
      ["cirrostratus fibratus", "stratocumulus undulatus", "cumulonimbus", "noctilucent clouds", "nimbostratus (2024)"],
      "Nirotiy",
    ),
    links: createBandcampLinks("/album/palette-of-clouds"),
    purchaseLinks: createPurchaseLinks("/album/palette-of-clouds", "TGEP-002"),
    isFeatured: true,
  },
  {
    slug: "kakusatsu-shoujo-3",
    title: {
      en: "KAKUSATSU SHOUJO 3",
      zh: "KAKUSATSU SHOUJO 3",
      jp: "KAKUSATSU SHOUJO 3",
    },
    heroTitle: {
      en: "KAKUSATSU\nSHOUJO 3",
      zh: "KAKUSATSU\nSHOUJO 3",
      jp: "KAKUSATSU\nSHOUJO 3",
    },
    artistName: "Thoughost",
    releaseType: "Compilation",
    releaseDate: "2024.08.12",
    modelNumber: "THGO-007",
    price: createBandcampPrice(1000),
    store: standardStore,
    coverImage: "/images/releases/kakusatsu-shoujo-3.jpg",
    heroImage: "/images/releases/kakusatsu-shoujo-3.jpg",
    summary: {
      en: "The third chapter in Thoughost’s signature compilation line pushes anime-sampled chaos, lolicore pressure, and violent-cute contrast into a sharper collective form.",
      zh: "Thoughost 标志性系列的第三章，把动画采样、lolicore 压力与“暴力 × 可爱”的反差推到更锋利、更集体化的状态。",
      jp: "Thoughost を象徴するシリーズの第3章。アニメ・サンプル、lolicore の圧力、そして“暴力とかわいさ”の対比を、さらに鋭くまとめ上げた作品です。",
    },
    credits: {
      mastering: "Joulez",
      illustrator: "だんごむし",
      designer: "Konseki Takane",
    },
    tracklist: createTracklist([
      "ぶっこぬき音源！ブレイクコアで抜いてしまったサキュバス賀馬ちゃん！",
      "Sekarashikh",
      "DJ Momo is Nothing Without her TEK Feat.The Operation",
      "Tanuki-Mujina Incident",
      "クソアニメは、ニオイで分かりまするぞ",
      "Inversion",
      "しかのこシコシコ腰パンパン",
      "RmL3Th",
      "FOOTPRINTS -雨ノ宮-",
      "天狱",
    ]),
    tracks: createDetailedTracks([
      { number: "01", title: "ぶっこぬき音源！ブレイクコアで抜いてしまったサキュバス賀馬ちゃん！", artist: "M9RVEN, 望月真白" },
      { number: "02", title: "Sekarashikh", artist: "Moetek" },
      { number: "03", title: "DJ Momo is Nothing Without her TEK Feat.The Operation", artist: "DJ Momo" },
      { number: "04", title: "Tanuki-Mujina Incident", artist: "かたぎり" },
      { number: "05", title: "クソアニメは、ニオイで分かりまするぞ", artist: "nova+z" },
      { number: "06", title: "Inversion", artist: "Aki" },
      { number: "07", title: "しかのこシコシコ腰パンパン", artist: "潮音きつね_H" },
      { number: "08", title: "RmL3Th", artist: "Null Specification" },
      { number: "09", title: "FOOTPRINTS -雨ノ宮-", artist: "望月真白" },
      { number: "10", title: "天狱", artist: "Yakumo" },
    ]),
    links: createBandcampLinks("/album/kakusatsu-shoujo-3"),
    purchaseLinks: createPurchaseLinks("/album/kakusatsu-shoujo-3", "THGO-007"),
    isHero: true,
    isFeatured: true,
  },
  {
    slug: "ephemanent",
    title: {
      en: "Ephemanent",
      zh: "Ephemanent",
      jp: "Ephemanent",
    },
    artistName: "Thoughost",
    releaseType: "Compilation",
    releaseDate: "2024.04.28",
    modelNumber: "THGO-006",
    price: createBandcampPrice(1500),
    store: standardStore,
    coverImage: "/images/releases/ephemanent.jpg",
    heroImage: "/images/releases/ephemanent.jpg",
    summary: {
      en: "A freeform hardcore compilation that leans into velocity, edge glow, and cosmic melodrama without losing the emotional lift inside the rush.",
      zh: "一张以 freeform hardcore 为核心的合集，在高速推进、星体感光泽与戏剧化情绪之间保持强烈上升感。",
      jp: "Freeform Hardcore を軸にしたコンピレーション。疾走感、宇宙的なきらめき、そして感情の昂りを同時に押し出しています。",
    },
    credits: {
      mastering: "Joulez",
      illustrator: "铫",
      designer: "Konseki Takane",
    },
    tracklist: createTracklist([
      "Cinder Glade",
      "Beryl",
      "Angel Generator",
      "Garnet",
      "Universe Outsiderz",
      "So What",
      "Event Horizon",
      "Nightmare Trigger",
      "Berzerk",
      "Code Name:Macrocosmos",
      "沉渊低语 (Whispers of Looming Shadows)",
      "星冴ゆる霜穹",
      "Erotomania (除名システム Recover)",
      "Herzschlag (Heartbeat)",
    ]),
    tracks: createDetailedTracks([
      { number: "01", title: "Cinder Glade", artist: "DJ Momo & ちよもも" },
      { number: "02", title: "Beryl", artist: "Kokomochi" },
      { number: "03", title: "Angel Generator", artist: "Ouuuuuu" },
      { number: "04", title: "Garnet", artist: "KaKi" },
      { number: "05", title: "Universe Outsiderz", artist: "Normal1zer" },
      { number: "06", title: "So What", artist: "Project-G" },
      { number: "07", title: "Event Horizon", artist: "Hyphen" },
      { number: "08", title: "Nightmare Trigger", artist: "MiYAjY" },
      { number: "09", title: "Berzerk", artist: "Joulez" },
      { number: "10", title: "Code Name:Macrocosmos", artist: "Irish Kappa" },
      { number: "11", title: "沉渊低语 (Whispers of Looming Shadows)", artist: "Nirotiy" },
      { number: "12", title: "星冴ゆる霜穹", artist: "潮音きつね_H" },
      { number: "13", title: "Erotomania (除名システム Recover)", artist: "ETIA." },
      { number: "14", title: "Herzschlag (Heartbeat)", artist: "Nirotiy" },
    ]),
    links: createBandcampLinks("/album/ephemanent"),
    purchaseLinks: createPurchaseLinks("/album/ephemanent", "THGO-006"),
    isFeatured: true,
  },
  {
    slug: "16-48",
    title: {
      en: "16:48",
      zh: "16:48",
      jp: "16:48",
    },
    artistName: "Joulez",
    releaseType: "Album",
    releaseDate: "2023.05.02",
    modelNumber: "TGSL-001",
    price: createBandcampPrice(1500),
    store: standardStore,
    coverImage: "/images/releases/16-48.jpg",
    heroImage: "/images/releases/16-48.jpg",
    summary: {
      en: "Joulez’s first solo album gathers three years of writing into a diaristic electronic record where poetry, memory, and brittle digital emotion sit side by side.",
      zh: "Joulez 的首张个人专辑，把三年间的创作凝成一份电子日记，让诗句、记忆与脆弱的数字情绪并置出现。",
      jp: "Joulez の初ソロ・アルバム。3年分の制作を束ね、詩、記憶、そして壊れそうなデジタル感情をひとつの流れに収めています。",
    },
    credits: {
      producer: "Joulez",
      mastering: "Joulez",
      designer: "紺 aka Konseki Takane",
    },
    tracklist: createTracklist([
      "to Introduce…",
      "i love u / hate myself",
      "a.ll the things I love(d)",
      "continuous deep imagination",
      "sunset (another time)",
      "mermaid of crystal cave",
      "just like glass",
      "unmarked trace",
      "forget.bat",
      "p229 (an interlude)",
      "22-46 november 4th",
      "Or?",
    ]),
    tracks: createDetailedTracks([
      { number: "01", title: "to Introduce…", artist: "Joulez" },
      { number: "02", title: "i love u / hate myself", artist: "Joulez / 除名システム" },
      { number: "03", title: "a.ll the things I love(d)", artist: "Joulez" },
      { number: "04", title: "continuous deep imagination", artist: "Joulez" },
      { number: "05", title: "sunset (another time)", artist: "Joulez" },
      { number: "06", title: "mermaid of crystal cave", artist: "Joulez" },
      { number: "07", title: "just like glass", artist: "Joulez" },
      { number: "08", title: "unmarked trace", artist: "Joulez" },
      { number: "09", title: "forget.bat", artist: "Joulez / lola螺旯 / 除名システム" },
      { number: "10", title: "p229 (an interlude)", artist: "Joulez" },
      { number: "11", title: "22-46 november 4th", artist: "Joulez" },
      { number: "12", title: "Or?", artist: "Joulez / lola螺旯" },
    ]),
    links: createBandcampLinks("/album/16-48"),
    purchaseLinks: createPurchaseLinks("/album/16-48", "TGSL-001"),
    isFeatured: true,
  },
  {
    slug: "after-the-forerunner-e-p",
    title: {
      en: "After the Forerunner e.p.",
      zh: "After the Forerunner e.p.",
      jp: "After the Forerunner e.p.",
    },
    artistName: "Thoughost",
    releaseType: "EP",
    releaseDate: "2023.04.30",
    modelNumber: "TGEP-001",
    price: createBandcampPrice(500),
    store: standardStore,
    coverImage: "/images/releases/after-the-forerunner-e-p.jpg",
    heroImage: "/images/releases/after-the-forerunner-e-p.jpg",
    summary: {
      en: "A six-track EP framed as a response to influence, tracing what happens after inspiration becomes movement, discipline, and a shared path forward.",
      zh: "一张六曲 EP，以“在先驱之后”作为主题，把影响、继承与继续前行的意志写成更明确的集体轨迹。",
      jp: "“先駆者のあと”をテーマにした6曲入り EP。影響を受けた先から、自分たちの歩みが始まる瞬間をまとめています。",
    },
    credits: {
      mastering: "Joulez",
      designer: "Konseki Takane",
    },
    tracklist: createTracklist([
      "rotfeldzestroerer",
      "Lumos",
      "zentrifugale",
      "No Excuse",
      "You Are The One",
      "白华",
    ]),
    tracks: createDetailedTracks([
      { number: "01", title: "rotfeldzestroerer", artist: "Joulez" },
      { number: "02", title: "Lumos", artist: "Laxeno57" },
      { number: "03", title: "zentrifugale", artist: "Nirotiy" },
      { number: "04", title: "No Excuse", artist: "DJ Momo" },
      { number: "05", title: "You Are The One", artist: "Irish Kappa" },
      { number: "06", title: "白华", artist: "AiSS" },
    ]),
    links: createBandcampLinks("/album/after-the-forerunner-e-p"),
    purchaseLinks: createPurchaseLinks("/album/after-the-forerunner-e-p", "TGEP-001"),
    isFeatured: true,
  },
  {
    slug: "depressive-emotional-compilation",
    title: {
      en: "蒼 -depressive & emotional compilation-",
      zh: "蒼 -depressive & emotional compilation-",
      jp: "蒼 -depressive & emotional compilation-",
    },
    artistName: "Thoughost",
    releaseType: "Compilation",
    releaseDate: "2022.10.30",
    modelNumber: "THGO-005",
    price: createBandcampPrice(1500),
    store: standardStore,
    coverImage: "/images/releases/depressive-emotional-compilation.jpg",
    heroImage: "/images/releases/depressive-emotional-compilation.jpg",
    summary: {
      en: "A large-scale emotional compilation that gathers depressive, fragile, and inward-facing cuts into a deep blue sequence of collapse and endurance.",
      zh: "一张体量很大的情绪合集，把抑郁、脆弱与内向性的片段压进一整片深蓝色叙事之中。",
      jp: "抑鬱、脆さ、内向きの感情を集めた大規模コンピレーション。深い青の中で崩れかける感覚と持ちこたえる意志が並走します。",
    },
    credits: {
      mastering: "Joulez",
      illustrator: "枝乃間",
      designer: "Konseki Takane",
    },
    tracklist: createTracklist([
      "蒼~track 1 lost~",
      "I love u hate myself",
      "Não me lembro da última vez, que eu sai do meu quarto",
      "Mnemosyne",
      "Stale Incense",
      "Payphone",
      "kiss in october",
      "Dementia",
      "Core of Ascension [Single Vers.]",
      "私",
      "Solitray World",
      "fun^10 x int^40",
      "死声",
      "Obelisk",
      "zexistenze",
      "Endlessly Colorless",
      "SAD_POETRY",
      "Or from July 24th",
      "MeaningLess",
      "Anthropocene",
      "l'espoire  en",
    ]),
    tracks: createDetailedTracks([
      { number: "01", title: "蒼~track 1 lost~", artist: "望月真白" },
      { number: "02", title: "I love u hate myself", artist: "Joulez" },
      { number: "03", title: "Não me lembro da última vez, que eu sai do meu quarto", artist: "f1d31" },
      { number: "04", title: "Mnemosyne", artist: "l!a" },
      { number: "05", title: "Stale Incense", artist: "terminus" },
      { number: "06", title: "Payphone", artist: "Uhp1QVQ" },
      { number: "07", title: "kiss in october", artist: "Kawaii amen girl" },
      { number: "08", title: "Dementia", artist: "Holly" },
      { number: "09", title: "Core of Ascension [Single Vers.]", artist: "Ultima Aevum" },
      { number: "10", title: "私", artist: "Urtica_Ferox_" },
      { number: "11", title: "Solitray World", artist: "rbZodiacX" },
      { number: "12", title: "fun^10 x int^40", artist: "zot!k" },
      { number: "13", title: "死声", artist: "Nirotiy" },
      { number: "14", title: "Obelisk", artist: "ELECTR" },
      { number: "15", title: "zexistenze", artist: "wheatfox" },
      { number: "16", title: "Endlessly Colorless", artist: "oblivious" },
      { number: "17", title: "SAD_POETRY", artist: "illness liquor" },
      { number: "18", title: "Or from July 24th", artist: "Joulez" },
      { number: "19", title: "MeaningLess", artist: "CarameL." },
      { number: "20", title: "Anthropocene", artist: "Laxeno57" },
      { number: "21", title: "l'espoire  en", artist: "BLUE NOISE" },
    ]),
    links: createBandcampLinks("/album/depressive-emotional-compilation"),
    purchaseLinks: createPurchaseLinks("/album/depressive-emotional-compilation", "THGO-005"),
  },
  {
    slug: "kakusatsu-shoujo-2",
    title: {
      en: "KAKUSATSU SHOUJO 2",
      zh: "KAKUSATSU SHOUJO 2",
      jp: "KAKUSATSU SHOUJO 2",
    },
    artistName: "Thoughost",
    releaseType: "Compilation",
    releaseDate: "2022.04.24",
    modelNumber: "THGO-004",
    price: createBandcampPrice(1200),
    store: standardStore,
    coverImage: "/images/releases/kakusatsu-shoujo-2.jpg",
    heroImage: "/images/releases/kakusatsu-shoujo-2.jpg",
    summary: {
      en: "The second KAKUSATSU SHOUJO chapter locks breakcore shock, anime-source mania, and compilation sprawl into one of Thoughost’s defining releases.",
      zh: "KAKUSATSU SHOUJO 系列第二章，把 breakcore 冲击、动画源采样与合集式爆发力进一步推成 Thoughost 的代表作之一。",
      jp: "KAKUSATSU SHOUJO シリーズ第2章。ブレイクコアの衝撃、アニメ・サンプル由来の狂気、コンピレーション特有の熱量が強く噛み合った代表作です。",
    },
    credits: {
      mastering: "Joulez",
      illustrator: "だんごむし",
      designer: "Konseki Takane",
    },
    tracklist: createTracklist([
      "うに娘二次創作ガイドライン違反作品",
      "physching",
      "Cannibal Cooker",
      "Roppongi Crisis",
      "REGETNI",
      "天井から見ると",
      "Secrets",
      "#WE_STILL_LOVE_PERFUME",
      "Iconos Del Anime",
      "Aria'Grief Seed'",
      "殻殺 -Instant Bullet-",
      "Succubus Gabber",
      "There's no reality",
      "LET ME SAY SANK YOU",
    ]),
    tracks: createDetailedTracks([
      { number: "01", title: "うに娘二次創作ガイドライン違反作品", artist: "潮音きつね_H" },
      { number: "02", title: "physching", artist: "Lax1u57" },
      { number: "03", title: "Cannibal Cooker", artist: "Null Specification" },
      { number: "04", title: "Roppongi Crisis", artist: "pencil" },
      { number: "05", title: "REGETNI", artist: "Dz'Xa" },
      { number: "06", title: "天井から見ると", artist: "四度月白" },
      { number: "07", title: "Secrets", artist: "Aki" },
      { number: "08", title: "#WE_STILL_LOVE_PERFUME", artist: "かたぎり" },
      { number: "09", title: "Iconos Del Anime", artist: "GoldenEggs" },
      { number: "10", title: "Aria'Grief Seed'", artist: "Nirotiy" },
      { number: "11", title: "殻殺 -Instant Bullet-", artist: "望月真白" },
      { number: "12", title: "Succubus Gabber", artist: "M9RVEN" },
      { number: "13", title: "There's no reality", artist: "citybridge" },
      { number: "14", title: "LET ME SAY SANK YOU", artist: "二重死後磁場" },
    ]),
    links: createBandcampLinks("/album/kakusatsu-shoujo-2"),
    purchaseLinks: createPurchaseLinks("/album/kakusatsu-shoujo-2", "THGO-004"),
  },
  {
    slug: "s-l-v-t-mixture",
    title: {
      en: "S.L.V.T: MIXTURE",
      zh: "S.L.V.T: MIXTURE",
      jp: "S.L.V.T: MIXTURE",
    },
    artistName: "Nirotiy & 望月真白",
    releaseType: "Collaboration",
    releaseDate: "2022.03.12",
    modelNumber: "THGO-003",
    price: createBandcampPrice(800),
    store: standardStore,
    coverImage: "/images/releases/s-l-v-t-mixture.jpg",
    heroImage: "/images/releases/s-l-v-t-mixture.jpg",
    summary: {
      en: "A split release from Nirotiy and 望月真白, built from cold synthetic mass, dark halation, and club tracks that keep mutating under pressure.",
      zh: "Nirotiy 与 望月真白的 split 作品，以冷质合成器、暗色晕光与不断变形的俱乐部结构组成一整块无机体。",
      jp: "Nirotiy と 望月真白によるスプリット作品。冷たい合成音、暗いハレーション、圧力の中で変形し続けるクラブ・トラックが核になっています。",
    },
    credits: {
      mastering: "Joulez",
      illustrator: "Nirotiy",
      designer: "Konseki Takane",
    },
    tracklist: createTracklist([
      "Verwirrung (Confusion) - Club Edit",
      "CHAOSHAN WISEGUYS",
      "Jiehkki (Glacier)",
      "INFERNAL AFFAIRS",
      "Hollow Heaven Underneath",
      "Bluntungen (Blood)",
      "Verwirrung - 空読無 白眼 REMIX",
      "INFERNAL AFFAIRS - Coredump Breaks REMIX",
      "MEGA BANGiN TUNES BATT1E",
      "Jiehkki (Glacier) - D3llketa MaxhIro REMIXXX",
    ]),
    tracks: createDetailedTracks([
      { number: "01", title: "Verwirrung (Confusion) - Club Edit", artist: "Nirotiy" },
      { number: "02", title: "CHAOSHAN WISEGUYS", artist: "DJ MASHIRO (2)" },
      { number: "03", title: "Jiehkki (Glacier)", artist: "Nirotiy" },
      { number: "04", title: "INFERNAL AFFAIRS", artist: "望月真白" },
      { number: "05", title: "Hollow Heaven Underneath", artist: "望月真白 ft. Nirotiy" },
      { number: "06", title: "Bluntungen (Blood)", artist: "Nirotiy" },
      { number: "07", title: "Verwirrung - 空読無 白眼 REMIX", artist: "Nirotiy" },
      { number: "08", title: "INFERNAL AFFAIRS - Coredump Breaks REMIX", artist: "望月真白" },
      { number: "09", title: "MEGA BANGiN TUNES BATT1E", artist: "The DJ 白手 Producer (2)" },
      { number: "10", title: "Jiehkki (Glacier) - D3llketa MaxhIro REMIXXX", artist: "Nirotiy" },
    ]),
    links: createBandcampLinks("/album/s-l-v-t-mixture"),
    purchaseLinks: createPurchaseLinks("/album/s-l-v-t-mixture", "THGO-003"),
  },
  {
    slug: "trixxck",
    title: {
      en: "TRIXXCK",
      zh: "TRIXXCK",
      jp: "TRIXXCK",
    },
    artistName: "Thoughost; Silent Xords",
    releaseType: "Collaboration",
    releaseDate: "2021.11.03",
    modelNumber: "TGSP-001",
    price: createBandcampPrice(500),
    store: standardStore,
    coverImage: "/images/releases/trixxck.jpg",
    heroImage: "/images/releases/trixxck.jpg",
    summary: {
      en: "A Thoughost × Silent Xords Halloween collaboration that runs on horror-coded synths, sharp visual grime, and overstimulated club tension.",
      zh: "Thoughost × Silent Xords 的万圣节联合作品，以惊悚感合成器、脏锐视觉和高度兴奋的俱乐部张力推进整张 EP。",
      jp: "Thoughost × Silent Xords によるハロウィン作品。ホラー感のあるシンセ、鋭い質感、過剰なテンションで押し切るコラボレーションです。",
    },
    credits: {
      mastering: "BlueWind",
      illustrator: "SCAF",
      designer: "Konseki Takane",
    },
    tracklist: createTracklist([
      "Intro",
      "MADCINE",
      "The Blood Spitted On Me",
      "ジレンマと枯れ葉",
      "Verdammnis",
      "Nothing but escape",
      "fish_man feat. Nirotiy",
    ]),
    tracks: createDetailedTracks([
      { number: "01", title: "Intro", artist: "Nirotiy" },
      { number: "02", title: "MADCINE", artist: "Nirotiy" },
      { number: "03", title: "The Blood Spitted On Me", artist: "BlueWind" },
      { number: "04", title: "ジレンマと枯れ葉", artist: "DJ Mashiro (2)" },
      { number: "05", title: "Verdammnis", artist: "Nirotiy" },
      { number: "06", title: "Nothing but escape", artist: "Black201" },
      { number: "07", title: "fish_man feat. Nirotiy", artist: "潮音きつね_H" },
    ]),
    links: createBandcampLinks("/album/trixxck"),
    purchaseLinks: createPurchaseLinks("/album/trixxck", "TGSP-001"),
  },
  {
    slug: "ground-attack",
    title: {
      en: "GROUND ATTACK!!!",
      zh: "GROUND ATTACK!!!",
      jp: "GROUND ATTACK!!!",
    },
    artistName: "Thoughost",
    releaseType: "Compilation",
    releaseDate: "2021.04.05",
    modelNumber: "THGO-002",
    price: createBandcampPrice(1000),
    store: standardStore,
    coverImage: "/images/releases/ground-attack.jpg",
    heroImage: "/images/releases/ground-attack.jpg",
    summary: {
      en: "A hard-charging compilation focused on funkot, hard bass, donk, and tribecore, keeping every cut bright, unruly, and physically direct.",
      zh: "一张围绕 funkot、hard bass、donk 与 tribecore 展开的高压合集，整体明亮、躁动，而且非常直接。",
      jp: "Funkot、Hard Bass、Donk、Tribecore を前面に出した攻撃的なコンピレーション。全編を通して明るく、荒々しく、身体的です。",
    },
    credits: {
      mastering: "Joulez, Project Nirvana",
      illustrator: "SHIKA",
      designer: "Konseki Takane",
    },
    tracklist: createTracklist([
      "quick intro to 2021 mashup meta",
      "massage seat",
      "Barbie Disco Tribe",
      "BF",
      "Vertigo",
      "Wrench Mind",
      "ロシア Donky Rave",
      "Cherrylike",
      "TWINS",
      "Yarasete Yuri Girl",
      "fallen",
      "Hypoxia_Mrs.SYR",
    ]),
    tracks: createDetailedTracks([
      { number: "01", title: "quick intro to 2021 mashup meta", artist: "jakka" },
      { number: "02", title: "massage seat", artist: "Black201" },
      { number: "03", title: "Barbie Disco Tribe", artist: "Aki" },
      { number: "04", title: "BF", artist: "hayato87b" },
      { number: "05", title: "Vertigo", artist: "Liet NRC" },
      { number: "06", title: "Wrench Mind", artist: "totsumal" },
      { number: "07", title: "ロシア Donky Rave", artist: "★Lolitwinx★" },
      { number: "08", title: "Cherrylike", artist: "ELECTR" },
      { number: "09", title: "TWINS", artist: "4nzu" },
      { number: "10", title: "Yarasete Yuri Girl", artist: "Moetek" },
      { number: "11", title: "fallen", artist: "citybridge" },
      { number: "12", title: "Hypoxia_Mrs.SYR", artist: "潮音きつね" },
    ]),
    links: createBandcampLinks("/album/ground-attack"),
    purchaseLinks: createPurchaseLinks("/album/ground-attack", "THGO-002"),
  },
  {
    slug: "perpetual-status",
    title: {
      en: "Perpetual Status -転生する天使-",
      zh: "Perpetual Status -転生する天使-",
      jp: "Perpetual Status -転生する天使-",
    },
    artistName: "DJ Mashiro (2)",
    releaseType: "Single",
    releaseDate: "2020.09.09",
    price: nameYourPrice,
    store: {
      en: "Thoughost Bandcamp",
      zh: "Thoughost Bandcamp",
      jp: "Thoughost Bandcamp",
    },
    coverImage: "/images/releases/perpetual-status.jpg",
    heroImage: "/images/releases/perpetual-status.jpg",
    summary: {
      en: "A standalone cut for a cult denpa-galgame reference point, balancing trance-like uplift with a darker reincarnation motif underneath.",
      zh: "一首独立单曲，以电波系游戏的情绪坐标为背景，在上扬感与更阴暗的“转生”主题之间保持平衡。",
      jp: "カルト的な電波系ゲームへの視線を含んだ単曲。上昇感のある流れの下で、“転生”のイメージがじわりと沈んでいます。",
    },
    tracklist: createTracklist(["Perpetual Status -転生する天使-"]),
    tracks: createUniformArtistTracks(["Perpetual Status -転生する天使-"], "DJ Mashiro (2)"),
    links: createBandcampLinks("/track/perpetual-status"),
    purchaseLinks: createPurchaseLinks("/track/perpetual-status"),
  },
  {
    slug: "series-planet-exploration-miranda",
    title: {
      en: "Series Planet Exploration - Miranda -",
      zh: "Series Planet Exploration - Miranda -",
      jp: "Series Planet Exploration - Miranda -",
    },
    artistName: "Nirotiy",
    releaseType: "Single",
    releaseDate: "2020.07.10",
    modelNumber: "TGSG-001",
    price: nameYourPrice,
    store: standardStore,
    coverImage: "/images/releases/series-planet-exploration-miranda.jpg",
    heroImage: "/images/releases/series-planet-exploration-miranda.jpg",
    summary: {
      en: "A planet-exploration single inspired by Miranda and Verona Rupes, translating distance, scale, and fracture into a focused sci-fi rush.",
      zh: "以天王星卫星 Miranda 与 Verona Rupes 为灵感的科幻单曲，把遥远尺度、断崖意象与探索欲凝成一次集中的推进。",
      jp: "ミランダとヴェローナ・ルーペスを着想源にした惑星探査シングル。距離感、巨大さ、破砕のイメージを一点集中の勢いへ変換しています。",
    },
    tracklist: createTracklist(["Series Planet Exploration - Miranda -"]),
    tracks: createUniformArtistTracks(["Series Planet Exploration - Miranda -"], "Nirotiy"),
    links: createBandcampLinks("/track/series-planet-exploration-miranda"),
    purchaseLinks: createPurchaseLinks("/track/series-planet-exploration-miranda", "TGSG-001"),
  },
  {
    slug: "kakusatsu-shoujo",
    title: {
      en: "KAKUSATSU SHOUJO",
      zh: "KAKUSATSU SHOUJO",
      jp: "KAKUSATSU SHOUJO",
    },
    artistName: "Thoughost",
    releaseType: "Compilation",
    releaseDate: "2020.06.05",
    modelNumber: "THGO-001",
    price: createBandcampPrice(800),
    store: standardStore,
    coverImage: "/images/releases/kakusatsu-shoujo.jpg",
    heroImage: "/images/releases/kakusatsu-shoujo.jpg",
    summary: {
      en: "The original entry in the KAKUSATSU SHOUJO line, laying down the project’s lolicore-heavy identity with manic energy and anime-sourced rupture.",
      zh: "KAKUSATSU SHOUJO 系列的起点，用 lolicore 导向的狂躁能量与动画采样式断裂感，奠定了整个项目的早期轮廓。",
      jp: "KAKUSATSU SHOUJO シリーズの原点。lolicore 的な狂騒とアニメ・サンプル由来の破断感で、この企画の初期輪郭を定めた作品です。",
    },
    credits: {
      mastering: "iOM",
      illustrator: "桜都あるす",
      designer: "Konseki Takane",
    },
    tracklist: createTracklist([
      "DigDigすぴーど243.4⁉︎_管人の闇a.k.a.ナカノヒト",
      "家族会議",
      "Senpai , I want your amen break!!!!♡",
      "アーメンとペトラ",
      "HITENSION+",
      "STRONG 280",
      "Miu Gakuen Tennis",
      "Warp A null",
      "Never Ends",
    ]),
    tracks: createDetailedTracks([
      { number: "01", title: "DigDigすぴーど243.4⁉︎_管人の闇a.k.a.ナカノヒト", artist: "潮音きつね_H" },
      { number: "02", title: "家族会議", artist: "uet" },
      { number: "03", title: "Senpai , I want your amen break!!!!♡", artist: "Nirotiy" },
      { number: "04", title: "アーメンとペトラ", artist: "蛇壊乃音" },
      { number: "05", title: "HITENSION+", artist: "Dz'Xa" },
      { number: "06", title: "STRONG 280", artist: "かたぎり" },
      { number: "07", title: "Miu Gakuen Tennis", artist: "Davidsan as hino_amane" },
      { number: "08", title: "Warp A null", artist: "Lzie" },
      { number: "09", title: "Never Ends", artist: "citybridge" },
    ]),
    links: createBandcampLinks("/album/kakusatsu-shoujo"),
    purchaseLinks: createPurchaseLinks("/album/kakusatsu-shoujo", "THGO-001"),
  },
];
